#!/usr/bin/env python
""" Converts JSON generated by sloth image annotation tool to a
csv file that adheres to MOT Challenge benchmark
"""
import sys
import json
import csv


def json2csv(data_path, out_path):
    with open(data_path) as data, open(out_path, 'wb') as csv_file:
        rows = []
        data = json.load(data)
        writer = csv.writer(csv_file)
        for i, frame in enumerate(data):
            for obj in frame['annotations']:
                row = [i + 1, obj['id'], obj['x'], obj['y'],
                       obj['width'], obj['height'], -1, -1, -1, -1]
                rows.append(row)
        writer.writerows(rows)


if __name__ == '__main__':
    if len(sys.argv) < 3:
        print("Please specify input JSON and output destination")
        exit()
    data_path = sys.argv[1]
    out_path = sys.argv[2]
    json2csv(data_path, out_path)
